POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhcm1hIiwiaWQiOiI2MGNiODI1YzMyZDVlYjMxMDEwMzNjMzYiLCJpYXQiOjE2MjQyNjIyMDl9.bHRvRUc2-HmzeTJlJ5zduU9FPff2ZcKKpiu-1wghYjI

{
    "title": "KISSABLOGI",
    "author": "kristiina",
    "url": "www.funski.fi",
    "likes": 120

}